name: Main
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set trace-start
        id: set-trace-start
        run: |
          echo ::set-output name=trace-start::$(date +%s)

  plan:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - uses: honeycombio/gha-buildevents@v2
        with:
          apikey: ${{ secrets.HONEYCOMB_BUILDEVENTS_API_KEY }}
          dataset: gha-buildevents_integration
          status: ${{ job.status }}
      - name: Echo
        run: echo "Hello, world!"
      - name: Sleep
        run: sleep 10

  plan2:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - uses: honeycombio/gha-buildevents@v2
        with:
          apikey: ${{ secrets.HONEYCOMB_BUILDEVENTS_API_KEY }}
          dataset: gha-buildevents_integration
          status: ${{ job.status }}
      - name: Echo
        run: echo "Hello, world!"
      - name: Sleep
        run: sleep 10

  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [plan, plan2]
    steps:
      - uses: actions/checkout@v3
      - uses: honeycombio/gha-buildevents@v2
        with:
          apikey: ${{ secrets.HONEYCOMB_BUILDEVENTS_API_KEY }}
          dataset: gha-buildevents_integration
          status: ${{ job.status }}
      - name: Echo
        run: echo "Hello, world!"
      - name: Sleep
        run: sleep 10

  end-trace:
    name: End Trace
    runs-on: ubuntu-latest
    needs: [setup, plan, plan2, deploy]
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/workflow-conclusion-action@v3
      - name: Buildevents
        uses: ./
        with:
          apikey: ${{ secrets.HONEYCOMB_BUILDEVENTS_API_KEY }}
          dataset: gha-buildevents_integration
          status: ${{ env.WORKFLOW_CONCLUSION }}
          trace-start: ${{ needs.setup.outputs.trace-start}}
