name: Main
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main-job:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: honeycombio/gha-buildevents@v2
        with:
          apikey: ${{ secrets.HONEYCOMB_BUILDEVENTS_API_KEY }}
          dataset: gha-buildevents_integration
          status: ${{ job.status }}
      - name: Echo
        run: echo "Hello, world!"
      - name: Sleep
        run: sleep 10
